'use strict';

const React = require('react');
const { formatDuration, FINISH_STATUS_LABELS } = require('@easyphrf/shared');
const { styles } = require('./styles');

const h = React.createElement;
const FOOTER = 'Generated by EasyPHRF — easyphrf.com';

// Column layout shared by header and body rows.
const COLUMNS = [
  { key: 'place', label: 'Place', width: '8%' },
  { key: 'boat', label: 'Boat Name', width: '24%' },
  { key: 'sail', label: 'Sail #', width: '13%' },
  { key: 'skipper', label: 'Skipper', width: '23%' },
  { key: 'phrf', label: 'PHRF', width: '10%' },
  { key: 'elapsed', label: 'Elapsed', width: '11%' },
  { key: 'corrected', label: 'Corrected', width: '11%' },
];

/**
 * Build the document tree. Receives the @react-pdf primitives so this module
 * never imports the ESM renderer at require-time.
 */
function buildDocument({ Document, Page, Text, View }, detail, club) {
  const headerRow = () =>
    h(
      View,
      { style: [styles.row, styles.headRow] },
      COLUMNS.map((c, i) =>
        h(View, { style: [styles.cell, { width: c.width }], key: i }, h(Text, { style: styles.headCell }, c.label))
      )
    );

  const entryRow = (entry, oneDesign, idx) => {
    const finished = entry.finish_status === 'finished';
    const phrfLabel =
      (entry.inferred ? '*' : '') + (entry.override_applied ? '†' : '') + String(entry.rating_used ?? '');
    const values = {
      place: entry.fleet_place != null ? String(entry.fleet_place) : '—',
      boat: entry.boat_name || '',
      sail: entry.sail_number || '',
      skipper: entry.skipper_name || '',
      phrf: oneDesign ? '—' : phrfLabel,
      elapsed: finished ? formatDuration(entry.elapsed_seconds) : FINISH_STATUS_LABELS[entry.finish_status] || '—',
      corrected: finished && !oneDesign ? formatDuration(entry.corrected_seconds) : '—',
    };
    return h(
      View,
      { style: styles.row, key: idx },
      COLUMNS.map((c, i) => h(View, { style: [styles.cell, { width: c.width }], key: i }, h(Text, {}, values[c.key])))
    );
  };

  const fleetSection = (fleet) => {
    const oneDesign = fleet.fleet_type === 'one_design';
    const finishers = fleet.entries.filter((e) => e.finish_status === 'finished');
    const others = fleet.entries.filter((e) => e.finish_status !== 'finished');
    const ordered = [...finishers, ...others];
    return h(
      View,
      { style: styles.section, key: fleet.fleet_id, wrap: false },
      h(Text, { style: styles.sectionTitle }, `${fleet.name}${oneDesign ? ' (One-Design)' : ''}`),
      h(View, { style: styles.table }, headerRow(), ordered.map((e, i) => entryRow(e, oneDesign, i)))
    );
  };

  const dateStr = detail.race_date ? String(detail.race_date).slice(0, 10) : '';
  const children = [
    h(Text, { style: styles.clubName, key: 'club' }, club.name),
    h(Text, { style: styles.title, key: 'title' }, detail.name),
    h(
      Text,
      { style: styles.subtitle, key: 'sub' },
      [dateStr, detail.start_type, detail.race_distance ? `${detail.race_distance} nm` : null]
        .filter(Boolean)
        .join('  •  ')
    ),
  ];

  if (detail.status === 'revised') {
    children.push(
      h(
        View,
        { style: styles.revision, key: 'rev' },
        h(Text, { style: styles.revisionTitle }, 'Results Revised'),
        h(
          Text,
          { style: styles.revisionBody },
          `${detail.revision_notes || ''}${
            detail.revised_at ? `  (${String(detail.revised_at).slice(0, 19).replace('T', ' ')})` : ''
          }`
        )
      )
    );
  }

  detail.fleets.forEach((fleet) => children.push(fleetSection(fleet)));

  if (detail.has_multiple_phrf_fleets && detail.overall && detail.overall.length) {
    const overallFleet = {
      fleet_id: 'overall',
      name: 'Overall PHRF Standings',
      fleet_type: 'phrf',
      entries: detail.overall.map((e) => ({ ...e, fleet_place: e.overall_place })),
    };
    children.push(fleetSection(overallFleet));
  }

  children.push(h(Text, { style: styles.footer, key: 'footer', fixed: true }, FOOTER));

  return h(Document, {}, h(Page, { size: 'A4', style: styles.page }, children));
}

/** Render a race-results PDF to a Buffer. */
async function renderRaceResultsPdf(detail, club) {
  const ReactPDF = await import('@react-pdf/renderer');
  const doc = buildDocument(ReactPDF, detail, club);
  return ReactPDF.renderToBuffer(doc);
}

module.exports = { renderRaceResultsPdf, buildDocument };
