'use strict';

const React = require('react');
const { styles } = require('./styles');

const h = React.createElement;
const FOOTER = 'Generated by EasyPHRF — easyphrf.com';

function buildDocument({ Document, Page, Text, View }, data, club) {
  const { series, races } = data;
  // Support both new fleetStandings and old flat standings
  const fleetSections =
    data.fleetStandings && data.fleetStandings.length > 0
      ? data.fleetStandings
      : [{ fleetName: null, standings: data.standings || [] }];

  const fixedCols = [
    { label: 'Rank', width: '8%' },
    { label: 'Boat', width: '24%' },
    { label: 'Skipper', width: '22%' },
    { label: 'Total', width: '10%' },
  ];
  const raceColWidth = `${Math.max(6, Math.floor(36 / Math.max(races.length, 1)))}%`;

  const headerRow = h(
    View,
    { style: [styles.row, styles.headRow], key: 'head' },
    fixedCols.map((c, i) =>
      h(View, { style: [styles.cell, { width: c.width }], key: `f${i}` }, h(Text, { style: styles.headCell }, c.label))
    ),
    races.map((r, i) =>
      h(View, { style: [styles.cell, { width: raceColWidth }], key: `r${i}` }, h(Text, { style: styles.headCell }, `R${i + 1}`))
    )
  );

  const buildBodyRows = (standings) =>
    standings.map((s, rowIdx) => {
      const perRaceByRace = new Map((s.perRace || []).map((p) => [p.raceId, p]));
      const raceCells = races.map((r, i) => {
        const p = perRaceByRace.get(r.race_id);
        const label = p ? String(p.points) : '—';
        const style = p && p.dropped ? { textDecoration: 'line-through', color: '#94a3b8' } : {};
        return h(View, { style: [styles.cell, { width: raceColWidth }], key: `c${i}` }, h(Text, { style }, label));
      });
      return h(
        View,
        { style: styles.row, key: rowIdx },
        h(View, { style: [styles.cell, { width: '8%' }], key: 'rank' }, h(Text, {}, s.rank != null ? String(s.rank) : '—')),
        h(View, { style: [styles.cell, { width: '24%' }], key: 'boat' }, h(Text, {}, s.boat ? s.boat.boat_name : s.boatId)),
        h(View, { style: [styles.cell, { width: '22%' }], key: 'skip' }, h(Text, {}, s.boat ? s.boat.skipper_name : '')),
        h(View, { style: [styles.cell, { width: '10%' }], key: 'tot' }, h(Text, {}, String(s.total_points))),
        raceCells
      );
    });

  const sections = fleetSections.map((fs, fsIdx) => {
    const headerLabel = fs.fleetName
      ? h(Text, { style: { fontSize: 10, fontWeight: 'bold', marginTop: 12, marginBottom: 4, color: '#475569' }, key: `fh${fsIdx}` }, fs.fleetName)
      : null;
    const bodyRows = buildBodyRows(fs.standings);
    return h(
      View,
      { key: `fs${fsIdx}`, style: { marginBottom: 12 } },
      ...(headerLabel ? [headerLabel] : []),
      h(View, { style: [styles.table, styles.section], key: `tbl${fsIdx}` }, headerRow, bodyRows)
    );
  });

  return h(
    Document,
    {},
    h(
      Page,
      { size: 'A4', style: styles.page },
      h(Text, { style: styles.clubName, key: 'club' }, club.name),
      h(Text, { style: styles.title, key: 'title' }, series.name),
      h(Text, { style: styles.subtitle, key: 'sub' }, `Season ${series.season_year}`),
      ...sections,
      h(Text, { style: styles.footer, key: 'footer', fixed: true }, FOOTER)
    )
  );
}

/** Render a series-standings PDF to a Buffer. */
async function renderSeriesStandingsPdf(data, club) {
  const ReactPDF = await import('@react-pdf/renderer');
  const doc = buildDocument(ReactPDF, data, club);
  return ReactPDF.renderToBuffer(doc);
}

module.exports = { renderSeriesStandingsPdf, buildDocument };
